### ISSUE TITLE
[BUG]  npx @shopware-pwa/cli init FAILS on new install

### ISSUE THREAD

**Issue by rrrodzilla** [vuestorefront/shopware-pwa#1311]
**### Describe the bug**
running: `npx @shopware-pwa/cli init` fails with the following error: 
```
npx @shopware-pwa/cli init
✔ Shopware instance address: · https://api.mydomain.com
✔ Shopware instance access token: · mytoken
✔ Which version you'd like to use: · latest stable (recommended)
✔ Preparing Nuxt project
⠧ Updating configuration for option: latest stable (recommended)/home/.npm/_npx/308796/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: Command failed: yarn add -D @shopware-pwa/nuxt-module@latest
warning @shopware-pwa/nuxt-module > @nuxt/types > @types/autoprefixer > @types/browserslist@4.15.0: This is a stub types definition. browserslist provides its own type definitions, so you do not need this installed.
warning @shopware-pwa/nuxt-module > @shopware-pwa/cli > gluegun > apisauce > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > vue-drag-drop > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning "@shopware-pwa/nuxt-module > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
warning "@shopware-pwa/nuxt-module > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning "@shopware-pwa/nuxt-module > @babel/plugin-proposal-nullish-coalescing-operator@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@shopware-pwa/nuxt-module > @babel/plugin-proposal-optional-chaining@7.12.7" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @vue/test-utils@1.1.2" has unmet peer dependency "vue@2.x".
warning " > @vue/test-utils@1.1.2" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@26.6.3" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@26.6.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-config-prettier@7.2.0" has unmet peer dependency "eslint@>=7.0.0".
warning " > eslint-plugin-prettier@3.3.1" has unmet peer dependency "eslint@>=5.0.0".
warning " > vue-jest@3.0.7" has unmet peer dependency "vue@^2.x".
warning " > vue-jest@3.0.7" has unmet peer dependency "vue-template-compiler@^2.x".
warning "@shopware-pwa/nuxt-module > @nuxt/typescript-build > ts-loader@8.0.14" has unmet peer dependency "webpack@*".
warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > sass-loader@10.1.1" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > vue2-leaflet@2.6.0" has unmet peer dependency "@types/leaflet@^1.5.7".
error /home/Projects/my-pwa/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/Projects/my-pwa/node_modules/node-sass
Output:
Building: /usr/local/bin/node /home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/bin/node',
gyp verb cli   '/home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.13.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/Projects/my-pwa/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/Projects/my-pwa/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/Projects/my-pwa/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:181:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/home/Projects/my-pwa/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/home/Projects/my-pwa/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/home/Projects/my-pwa/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/which/which.js:89:16
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:181:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Linux 5.9.16-1-MANJARO
gyp ERR! command "/usr/local/bin/node" "/home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/Projects/my-pwa/node_modules/node-sass
gyp ERR! node -v v14.13.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn add -D @shopware-pwa/nuxt-module@latest',
  stdout: 'yarn add v1.22.10\n' +
    '[1/4] Resolving packages...\n' +
    '[2/4] Fetching packages...\n' +
    'info fsevents@2.3.1: The platform "linux" is incompatible with this module.\n' +
    'info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.\n' +
    'info fsevents@1.2.13: The platform "linux" is incompatible with this module.\n' +
    'info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.\n' +
    '[3/4] Linking dependencies...\n' +
    '[4/4] Building fresh packages...\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n',
  stderr: 'warning @shopware-pwa/nuxt-module > @nuxt/types > @types/autoprefixer > @types/browserslist@4.15.0: This is a stub types definition. browserslist provides its own type definitions, so you do not need this installed.\n' +
    'warning @shopware-pwa/nuxt-module > @shopware-pwa/cli > gluegun > apisauce > axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410\n' +
    'warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > vue-drag-drop > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.\n' +
    'warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
    'warning @shopware-pwa/nuxt-module > @shopware-pwa/default-theme > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
    'warning "@shopware-pwa/nuxt-module > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".\n' +
    'warning "@shopware-pwa/nuxt-module > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".\n' +
    'warning "@shopware-pwa/nuxt-module > @babel/plugin-proposal-nullish-coalescing-operator@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "@shopware-pwa/nuxt-module > @babel/plugin-proposal-optional-chaining@7.12.7" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning " > @vue/test-utils@1.1.2" has unmet peer dependency "vue@2.x".\n' +
    'warning " > @vue/test-utils@1.1.2" has unmet peer dependency "vue-template-compiler@^2.x".\n' +
    'warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning " > babel-jest@26.6.3" has unmet peer dependency "@babel/core@^7.0.0".\n' +
    'warning "babel-jest > babel-preset-jest@26.6.2" has unmet peer dependency "@babel/core@^7.0.0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".\n' +
    'warning " > eslint-config-prettier@7.2.0" has unmet peer dependency "eslint@>=7.0.0".\n' +
    'warning " > eslint-plugin-prettier@3.3.1" has unmet peer dependency "eslint@>=5.0.0".\n' +
    'warning " > vue-jest@3.0.7" has unmet peer dependency "vue@^2.x".\n' +
    'warning " > vue-jest@3.0.7" has unmet peer dependency "vue-template-compiler@^2.x".\n' +
    'warning "@shopware-pwa/nuxt-module > @nuxt/typescript-build > ts-loader@8.0.14" has unmet peer dependency "webpack@*".\n' +
    'warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > sass-loader@10.1.1" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".\n' +
    'warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".\n' +
    'warning "@shopware-pwa/nuxt-module > @shopware-pwa/default-theme > @storefront-ui/vue > vue2-leaflet@2.6.0" has unmet peer dependency "@types/leaflet@^1.5.7".\n' +
    'error /home/Projects/my-pwa/node_modules/node-sass: Command failed.\n' +
    'Exit code: 1\n' +
    'Command: node scripts/build.js\n' +
    'Arguments: \n' +
    'Directory: /home/Projects/my-pwa/node_modules/node-sass\n' +
    'Output:\n' +
    'Building: /usr/local/bin/node /home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=\n' +
    'gyp info it worked if it ends with ok\n' +
    'gyp verb cli [\n' +
    "gyp verb cli   '/usr/local/bin/node',\n" +
    "gyp verb cli   '/home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js',\n" +
    "gyp verb cli   'rebuild',\n" +
    "gyp verb cli   '--verbose',\n" +
    "gyp verb cli   '--libsass_ext=',\n" +
    "gyp verb cli   '--libsass_cflags=',\n" +
    "gyp verb cli   '--libsass_ldflags=',\n" +
    "gyp verb cli   '--libsass_library='\n" +
    'gyp verb cli ]\n' +
    'gyp info using node-gyp@3.8.0\n' +
    'gyp info using node@14.13.1 | linux | x64\n' +
    'gyp verb command rebuild []\n' +
    'gyp verb command clean []\n' +
    'gyp verb clean removing "build" directory\n' +
    'gyp verb command configure []\n' +
    'gyp verb check python checking for Python executable "python2" in the PATH\n' +
    'gyp verb `which` failed Error: not found: python2\n' +
    'gyp verb `which` failed     at getNotFoundError (/home/Projects/my-pwa/node_modules/which/which.js:13:12)\n' +
    'gyp verb `which` failed     at F (/home/Projects/my-pwa/node_modules/which/which.js:68:19)\n' +
    'gyp verb `which` failed     at E (/home/Projects/my-pwa/node_modules/which/which.js:80:29)\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/which/which.js:89:16\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/index.js:42:5\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/mode.js:8:5\n' +
    'gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:181:21)\n' +
    'gyp verb `which` failed  python2 Error: not found: python2\n' +
    'gyp verb `which` failed     at getNotFoundError (/home/Projects/my-pwa/node_modules/which/which.js:13:12)\n' +
    'gyp verb `which` failed     at F (/home/Projects/my-pwa/node_modules/which/which.js:68:19)\n' +
    'gyp verb `which` failed     at E (/home/Projects/my-pwa/node_modules/which/which.js:80:29)\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/which/which.js:89:16\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/index.js:42:5\n' +
    'gyp verb `which` failed     at /home/Projects/my-pwa/node_modules/isexe/mode.js:8:5\n' +
    'gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:181:21) {\n' +
    "gyp verb `which` failed   code: 'ENOENT'\n" +
    'gyp verb `which` failed }\n' +
    'gyp verb check python checking for Python executable "python" in the PATH\n' +
    'gyp verb `which` succeeded python /usr/bin/python\n' +
    'gyp ERR! configure error \n' +
    'gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];\n' +
    'gyp ERR! stack   File "<string>", line 1\n' +
    'gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];\n' +
    'gyp ERR! stack                       ^\n' +
    'gyp ERR! stack SyntaxError: invalid syntax\n' +
    'gyp ERR! stack \n' +
    'gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)\n' +
    'gyp ERR! stack     at ChildProcess.emit (events.js:314:20)\n' +
    'gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)\n' +
    'gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)\n' +
    'gyp ERR! System Linux 5.9.16-1-MANJARO\n' +
    'gyp ERR! command "/usr/local/bin/node" "/home/Projects/my-pwa/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="\n' +
    'gyp ERR! cwd /home/Projects/my-pwa/node_modules/node-sass\n' +
    'gyp ERR! node -v v14.13.1\n' +
    'gyp ERR! node-gyp -v v3.8.0\n' +
    'gyp ERR! not ok \n' +
    'Build failed with error code: 1\n'
}

```

**REPRO STEPS:**
Follow steps at: 
https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/
execute the following commands from your terminal:
```
mkdir my-pwa && cd my-pwa
npx @shopware-pwa/cli init
```

Enter shopware instance address: (your own backend address)
Enter instance access token: (your own access token)
Which version you'd like to use: choose latest stable (recommended)
After some time, process fails with error above

**### Additional context**
**Node 14.13.1
yarn 1.22.10
Python 3.9.1**

Fresh install of Manjaro (Arch Linux) on system as follows:
```
System:    Kernel: 5.9.16-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.20.5 Distro: Manjaro Linux 
Machine:   Type: Laptop System: Dell product: Latitude E7450 v: 01 serial: <superuser required> 
           Mobo: Dell model: 0D8H72 v: A00 serial: <superuser required> UEFI: Dell v: A04 date: 05/13/2015 
CPU:       Info: Dual Core model: Intel Core i5-5300U bits: 64 type: MT MCP L2 cache: 3 MiB 
           Speed: 1875 MHz min/max: 500/2900 MHz Core speeds (MHz): 1: 1875 2: 1535 3: 1891 4: 1901 
Graphics:  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.10 driver: loaded: intel unloaded: modesetting resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 5500 (BDW GT2) v: 4.6 Mesa 20.3.3 
           Sound Server: ALSA v: k5.9.16-1-MANJARO 
Drives:    Local Storage: total: 238.47 GiB used: 29.65 GiB (12.4%) 
Sensors:   System Temperatures: cpu: 58.0 C mobo: 45.0 C sodimm: SODIMM C 
           Fan Speeds (RPM): cpu: 3321 
Info:      Processes: 224 Uptime: 4d 4h 27m Memory: 7.67 GiB used: 5.44 GiB (70.9%) Shell: Bash inxi: 3.2.02 
```

**Comment by rrrodzilla** [comment]
UPDATE:
After trying many things over the past few hours I installed Python 2.7 and added a .npmrc file to a clean project directory to force the build process to use Python 2.7 and I finally got a different error message.  The .npmrc file contains only `python = "/usr/bin/python2.7"`

New error message is as follows:
```
Which version you'd like to use: · latest stable (recommended)
✔ Preparing Nuxt project
⠇ Updating configuration for option: latest stable (recommended)/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: file not found nuxt.config.js
    at /home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:183:23
    at step (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:33:23)
    at Object.next (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:14:53)
    at /home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:4:12)
    at readFile (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:179:12)
    at /home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:86:46
    at step (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:33:23)
    at Object.next (/home/.npm/_npx/6924/lib/node_modules/@shopware-pwa/cli/node_modules/gluegun/build/toolbox/patching-tools.js:14:53)

```

As an aside, I'm getting the distinct feeling that the [>10 minute quickstart](https://shopware-pwa-docs.vuestorefront.io/landing/getting-started/) and the [setup cheatsheet](https://shopware-pwa-docs.vuestorefront.io/landing/resources/cheatsheet.html) may be missing some system prerequisites. ;-)

**Comment by super-kamil** [comment]
Try using canary cli and master branch:

```
npx @shopware-pwa/cli@canary init
Which version you'd like to use: canary (current master branch)
```
On the "recommended" branch i get the error "nuxt config missing"

**Comment by cb-mfg** [comment]
Same issue for me, on both `@shopware-pwa/cli` as well as `@shopware-pwa/cli@canary`, no matter watch branch (latest stable / canary / local).

```
Error: Command failed: yarn add -D @shopware-pwa/cli@canary @shopware-pwa/composables@canary @shopware-pwa/helpers@canary @shopware-pwa/shopware-6-client@canary @shopware-pwa/default-theme@canary @shopware-pwa/nuxt-module@canary @shopware-pwa/theme-base@canary
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).

    at ChildProcess.exithandler (node:child_process:326:12)
    at ChildProcess.emit (node:events:378:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn add -D @shopware-pwa/cli@canary @shopware-pwa/composables@canary @shopware-pwa/helpers@canary @shopware-pwa/shopware-6-client@canary @shopware-pwa/default-theme@canary @shopware-pwa/nuxt-module@canary @shopware-pwa/theme-base@canary',
  stdout: 'yarn add v1.22.10\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n',
  stderr: 'error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).\n'
}
```

**Comment by patzick** [comment]
hey! Is this still an issue while invoking `init` command? On Node 14 this should work without problems. On node 15 this will be resolved with #1198.
Please let us know!

**Comment by patzick** [comment]
Closing this now, Node issue will be resolved with #1463

**Comment by super-kamil** [comment]
For me it works now since few weeks

**Comment by Almusamim** [comment]
I'm having same error! 
Is v0.9x not supposed to work with node 14? 

It is not even working on sandbox with same error https://codesandbox.io/s/shopware-pwa-v09x-gp02u?file=/README.md @patzick 


npm -v 7.20.1
node -v 14.17.1
Windows 10
```
C:\Users\Hadi\Playground\storefront>npx @shopware-pwa/cli@canary init
√ Shopware instance address: · https://shopware6-demo.vuestorefront.io
√ Shopware instance access token: · SWSCVJJET0RQAXFNBMTDZTV1OQ
√ Which version you'd like to use: · latest stable (recommended)
√ Preparing Nuxt project
√ Updating configuration for option: latest stable (recommended)
- Generating project filesC:\Users\Hadi\AppData\Roaming\npm\node_modules\@shopware-pwa\cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

Error: Path to copy doesn't exist C:\Users\Hadi\Playground\storefront\node_modules\@shopware-pwa\default-theme\store
    at generateNoSourceError (C:\Users\Hadi\AppData\Roaming\npm\node_modules\@shopware-pwa\cli\node_modules\fs-jetpack\lib\copy.js:52:15)
    at C:\Users\Hadi\AppData\Roaming\npm\node_modules\@shopware-pwa\cli\node_modules\fs-jetpack\lib\copy.js:170:15 {
  code: 'ENOENT'
}
```

**Comment by patzick** [comment]
hey @Almusamim! When did you fire this command?
The output of the canary should be completely different, demo instance addresses have changed and it shouldn't ask you which version to pick.

Maybe `npx` command on windows is caching some packages? Please clear the cache and run this command once again.

**Comment by Almusamim** [comment]
> hey @Almusamim! When did you fire this command?
> The output of the canary should be completely different, demo instance addresses have changed and it shouldn't ask you which version to pick.
> 
> Maybe `npx` command on windows is caching some packages? Please clear the cache and run this command once again.

The problem was that I installed @shopware-pwa/cli globally some time ago and updating it fixed the issue.

Thanks for the help, appreciate it :)
