### ISSUE TITLE
[BUG] Fresh installation not working

### ISSUE THREAD

**Issue by alpham8** [vuestorefront/shopware-pwa#1517]
### A fresh installation is not working
Nor `shopware-pwa` or `yarn dev` works. I started over again. I also did `git checkout` to the latest tag.

#### Steps to reproduce
- install or setup your environment. For me, it's docker using ddev.
- run `npx @shopware-pwa/cli@canary init`

Then you should see the following output:
```
npx @shopware-pwa/cli@canary init
✔ Shopware instance address: · http://ddev-example-sw6-web
✔ Shopware instance access token: · SWSCQ3FYEKUWYJV1OVZCQZVHVQ
✔ Which version you'd like to use: · ^0.8.2
✔ Preparing Nuxt project
✔ Updating configuration for option: ^0.8.2
✔ Generating project files
Please provide username and password for plugins authentication. You can leave the fields empty if connecting to demo instance or if you don't need plugins :)
✔ Shopware admin username: · demo
✔ Shopware admin password: · ****
✔ Do you want to allow dev mode for slots? (Don't use for production!) (y/N) · true
UNEXPECTED ERROR [object Object]
Error: Request failed with status code 404
    at createError (/home/alpham8/.npm/_npx/2054/lib/node_modules/@shopware-pwa/cli/build/extensions/plugins-extensions.js:380:19)
    at settle (/home/alpham8/.npm/_npx/2054/lib/node_modules/@shopware-pwa/cli/build/extensions/plugins-extensions.js:396:16)
    at IncomingMessage.handleStreamEnd (/home/alpham8/.npm/_npx/2054/lib/node_modules/@shopware-pwa/cli/build/extensions/plugins-extensions.js:2089:15)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'http://ddev-example-sw6-web/api/_action/pwa/dump-bundles',
    method: 'post',
    data: null,
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/x-www-form-urlencoded',
      Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJhZG1pbmlzdHJhdGlvbiIsImp0aSI6Ijk2NzJjMWVlYTU2MTkwZjdhNTc4Mjc1M2VjYWZkYjQxODMwMTNjYTU1MjFjZjE5ZDk0ZGYyMDdkMDY0NzdkMDE2NTUyMzIwZTJhMTQ2ZmFkIiwiaWF0IjoiMTYyMjEwNDIyOC4xNTA0NTIiLCJuYmYiOiIxNjIyMTA0MjI4LjE1MDQ1MyIsImV4cCI6IjE2MjIxMDQ4MjguMTQ4OTExIiwic3ViIjoiNzI4NDBjZjgwODcxNGM0Nzk5YjljOWI0YzRlOGFiZDEiLCJzY29wZXMiOlsid3JpdGUiLCJhZG1pbiJdfQ.QzVRENYWKNqah_V5KjdilJssdAJ9azbhsFlteS5AwBcHw1kxv6ID4ih1Gw5gxZZS6zycECJoh6QZ1qdkO7zR3RccPjfdk40yB1_n4AZgAwVpyshvFsBrhvMHyCdxrL_TDn8vBWOPK14R-ZxuAk20THjq9gwwMykpOim8Z7yNPK8mATumICf5FrSfDcNqvpSSern4UYOKS9YPkXtodjlt9ldikLsvkiSKrpmlpRiaEyaKDpJuEy9qGmeorp4JT8rJ0HROkZuS3kDKCL1NpwRBva_Un7u3YsOPSp3x96ePNLn7UP_kcWdQg6T0bDIg0IwctaxUHE6yjxE_YOUp8BlkjQ',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'ddev-example-sw6-web',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 1489,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /api/_action/pwa/dump-bundles HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/x-www-form-urlencoded\r\n' +
      'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJhZG1pbmlzdHJhdGlvbiIsImp0aSI6Ijk2NzJjMWVlYTU2MTkwZjdhNTc4Mjc1M2VjYWZkYjQxODMwMTNjYTU1MjFjZjE5ZDk0ZGYyMDdkMDY0NzdkMDE2NTUyMzIwZTJhMTQ2ZmFkIiwiaWF0IjoiMTYyMjEwNDIyOC4xNTA0NTIiLCJuYmYiOiIxNjIyMTA0MjI4LjE1MDQ1MyIsImV4cCI6IjE2MjIxMDQ4MjguMTQ4OTExIiwic3ViIjoiNzI4NDBjZjgwODcxNGM0Nzk5YjljOWI0YzRlOGFiZDEiLCJzY29wZXMiOlsid3JpdGUiLCJhZG1pbiJdfQ.QzVRENYWKNqah_V5KjdilJssdAJ9azbhsFlteS5AwBcHw1kxv6ID4ih1Gw5gxZZS6zycECJoh6QZ1qdkO7zR3RccPjfdk40yB1_n4AZgAwVpyshvFsBrhvMHyCdxrL_TDn8vBWOPK14R-ZxuAk20THjq9gwwMykpOim8Z7yNPK8mATumICf5FrSfDcNqvpSSern4UYOKS9YPkXtodjlt9ldikLsvkiSKrpmlpRiaEyaKDpJuEy9qGmeorp4JT8rJ0HROkZuS3kDKCL1NpwRBva_Un7u3YsOPSp3x96ePNLn7UP_kcWdQg6T0bDIg0IwctaxUHE6yjxE_YOUp8BlkjQ\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Host: ddev-example-sw6-web\r\n' +
      'Connection: close\r\n' +
      'Content-Length: 0\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/_action/pwa/dump-bundles',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://ddev-example-sw6-web/api/_action/pwa/dump-bundles',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'ddev-example-sw6-web',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://ddev-example-sw6-web/api/_action/pwa/dump-bundles',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      server: 'nginx',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      vary: 'Accept-Encoding',
      'cache-control': 'private',
      date: 'Thu, 27 May 2021 08:30:28 GMT',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE',
      'access-control-allow-headers': 'Content-Type,Authorization,sw-context-token,sw-access-key,sw-language-id,sw-version-id,sw-inheritance,fail-on-error,indexing-behavior,single-operation,sw-include-seo-urls',
      'access-control-expose-headers': 'Content-Type,Authorization,sw-context-token,sw-access-key,sw-language-id,sw-version-id,sw-inheritance,fail-on-error,indexing-behavior,single-operation,sw-include-seo-urls',
      'x-frame-options': 'deny',
      'x-debug-token': 'c85dfc',
      'x-debug-token-link': 'http://ddev-example-sw6-web/_profiler/c85dfc',
      'x-robots-tag': 'noindex',
      'x-symfony-cache': 'POST /api/_action/pwa/dump-bundles: pass'
    },
    config: {
      url: 'http://ddev-example-sw6-web/api/_action/pwa/dump-bundles',
      method: 'post',
      data: null,
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /api/_action/pwa/dump-bundles HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJhZG1pbmlzdHJhdGlvbiIsImp0aSI6Ijk2NzJjMWVlYTU2MTkwZjdhNTc4Mjc1M2VjYWZkYjQxODMwMTNjYTU1MjFjZjE5ZDk0ZGYyMDdkMDY0NzdkMDE2NTUyMzIwZTJhMTQ2ZmFkIiwiaWF0IjoiMTYyMjEwNDIyOC4xNTA0NTIiLCJuYmYiOiIxNjIyMTA0MjI4LjE1MDQ1MyIsImV4cCI6IjE2MjIxMDQ4MjguMTQ4OTExIiwic3ViIjoiNzI4NDBjZjgwODcxNGM0Nzk5YjljOWI0YzRlOGFiZDEiLCJzY29wZXMiOlsid3JpdGUiLCJhZG1pbiJdfQ.QzVRENYWKNqah_V5KjdilJssdAJ9azbhsFlteS5AwBcHw1kxv6ID4ih1Gw5gxZZS6zycECJoh6QZ1qdkO7zR3RccPjfdk40yB1_n4AZgAwVpyshvFsBrhvMHyCdxrL_TDn8vBWOPK14R-ZxuAk20THjq9gwwMykpOim8Z7yNPK8mATumICf5FrSfDcNqvpSSern4UYOKS9YPkXtodjlt9ldikLsvkiSKrpmlpRiaEyaKDpJuEy9qGmeorp4JT8rJ0HROkZuS3kDKCL1NpwRBva_Un7u3YsOPSp3x96ePNLn7UP_kcWdQg6T0bDIg0IwctaxUHE6yjxE_YOUp8BlkjQ\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: ddev-example-sw6-web\r\n' +
        'Connection: close\r\n' +
        'Content-Length: 0\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/_action/pwa/dump-bundles',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'ddev-example-sw6-web',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { errors: [Array] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
✔ Generating plugins files
Shopware languages refreshed
Plugins generated
CMS prepared
Shopware languages refreshed

Synchronize the domain's related config from backend (in order to build a domains.json file)
✔ Shopware admin username: · demo
✔ Shopware admin password: · ****
Unable to save a domains.json.
✔ Updating dependencies
Generated Shopware PWA project!
Type 'shopware-pwa dev' and start exploring
```

Any help to this issue would be great. We really like to use Shopware PWA.

Thanks in advice,

alpham8

**Comment by mkucmus** [comment]
hi @alpham8, thanks for reporting the issue.

At the first look I can found here a 404, caused by missing endpoint `/api/_action/pwa/dump-bundles`.
This endpoint is being added by installing a PWA plugin.
If it's not installed yet, please visit [the repository](https://github.com/elkmod/SwagShopwarePwa) and install the plugin first. Keep in mind that the versions should match your shopware-pwa.
