### ISSUE TITLE
[BUG] Typescript: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by meeshoogendoorn** [vuestorefront/shopware-pwa#1536]
### Describe the bug
Everytime i will run the `npx @shopware-pwa/cli@latest` i will get an error that the Maximum call stack size exceeded.

### Versions
PWA Version: `0.9.0`
Shopware version: `6.4`

### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2018",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ESNext", "ESNext.AsyncIterable", "DOM"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./.shopware-pwa/source/*"]
    },
    "types": ["@types/node", "@nuxt/types"]
  },
  "exclude": ["node_modules"]
}

```

### Stack trace

```bash
 ERROR  RangeError: Maximum call stack size exceeded                                                                                11:14:48

  at Object.getCheckFlags (node_modules/typescript/lib/typescript.js:18470:27)
  at addPropertyToElementList (node_modules/typescript/lib/typescript.js:48397:53)
  at createTypeNodesFromResolvedType (node_modules/typescript/lib/typescript.js:48384:25)
  at createTypeNodeFromObjectType (node_modules/typescript/lib/typescript.js:48190:35)
  at visitAndTransformType (node_modules/typescript/lib/typescript.js:48138:34)
  at createAnonymousTypeNode (node_modules/typescript/lib/typescript.js:48092:36)
  at typeToTypeNodeHelper (node_modules/typescript/lib/typescript.js:47989:28)
  at serializeReturnTypeForSignature (node_modules/typescript/lib/typescript.js:49181:24)
  at signatureToSignatureDeclarationHelper (node_modules/typescript/lib/typescript.js:48586:42)
  at addPropertyToElementList (node_modules/typescript/lib/typescript.js:48424:49)

```

### Extra information
This error occurred after the update from 0.8.2 to 0.9.0 i don't use any typescript in my code yet.

### Steps

1.  npx @shopware-pwa/cli@0.9.0 dev 
2. is see the following response 
```bash
 Using theme: @shopware-pwa/default-theme                                                                                          11:14:37

   ╭────────────────────────────────────────────╮
   │                                            │
   │   Nuxt @ v2.15.6                           │
   │                                            │
   │   ▸ Environment: development               │
   │   ▸ Rendering:   server-side               │
   │   ▸ Target:      server                    │
   │                                            │
   │   Listening: http://0.0.0.0:3000/   │
   │                                            │
   ╰────────────────────────────────────────────╯

ℹ Preparing project for development                                                                                                 11:14:38
ℹ Initial build may take a while                                                                                                    11:14:38
ℹ Discovered Components: .nuxt/components/readme.md                                                                                 11:14:38
✔ Builder initialized                                                                                                               11:14:38
✔ Nuxt files generated   


✔ Client
  Compiled successfully in 31.11s

✔ Server
  Compiled successfully in 27.78s


 ERROR  RangeError: Maximum call stack size exceeded                                                                                11:14:48

  at Object.getCheckFlags (node_modules/typescript/lib/typescript.js:18470:27)
  at addPropertyToElementList (node_modules/typescript/lib/typescript.js:48397:53)
  at createTypeNodesFromResolvedType (node_modules/typescript/lib/typescript.js:48384:25)
  at createTypeNodeFromObjectType (node_modules/typescript/lib/typescript.js:48190:35)
  at visitAndTransformType (node_modules/typescript/lib/typescript.js:48138:34)
  at createAnonymousTypeNode (node_modules/typescript/lib/typescript.js:48092:36)
  at typeToTypeNodeHelper (node_modules/typescript/lib/typescript.js:47989:28)
  at serializeReturnTypeForSignature (node_modules/typescript/lib/typescript.js:49181:24)
  at signatureToSignatureDeclarationHelper (node_modules/typescript/lib/typescript.js:48586:42)
  at addPropertyToElementList (node_modules/typescript/lib/typescript.js:48424:49)
```

**Comment by patzick** [comment]
thanks for bringing it up; looks like the problem with dependencies, please try the following steps:

1. update the version in `package.json`
2. `yarn upgrade`
3. `yarn shopware-pwa init`
4. `yarn dev` (do not use npx for anything else than init)

what else could help if not this:
* remove `node_modules` directory and `yarn.lock` file
* (DO BACKUP BEFORE) remove nuxt.config.js and invoke `npx @shopware-pwa/cli init`

if nothing from above works please show us your package.json and yarn.lock file

**Comment by meeshoogendoorn** [comment]
@patzick What node version is recommended for shopware-pwa 0.9.0?

I am using node@14.16.1 but when running yarn after regenrating it looks like error have to do with node version

**Comment by patzick** [comment]
@meeshoogendoorn Active LTS is recommended, currently, it's v14 and we're testing on it, so your version is good

**Comment by meeshoogendoorn** [comment]
Well The solutions you provided didn't work. So here is my package.json:

```json
{
  "name": "shopware-pwa-project",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "shopware-pwa dev",
    "build": "shopware-pwa build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest",
    "lint": "prettier --write '*.{js,vue}'"
  },
  "dependencies": {
    "@kippie/shopware-pwa-ecommerce": "1.0.34",
    "@mapbox/mapbox-gl-geocoder": "^4.7.0",
    "@nuxtjs/axios": "^5.13.4",
    "@nuxtjs/pwa": "^3.3.5",
    "@turf/turf": "^6.3.0",
    "core-js": "^3.12.1",
    "lite-youtube-embed": "^0.2.0",
    "mapbox-gl": "^2.2.0",
    "mixitup": "^3.3.1",
    "nuxt": "^2.15.6",
    "skeleton-screen-css": "^1.0.1",
    "v-lazy-image": "^1.4.0",
    "vuelidate": "^0.7.6"
  },
  "devDependencies": {
    "@shopware-pwa/nuxt-module": "^0.9.0",
    "@storefront-ui/vue": "0.10.5",
    "@vue/test-utils": "^1.2.0",
    "@vuelidate/core": "^2.0.0-alpha.17",
    "@vuelidate/validators": "^2.0.0-alpha.14",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^26.6.3",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "jest": "^26.6.3",
    "node-sass": "^5.0.0",
    "prettier": "^2.3.0",
    "vue-jest": "^3.0.7"
  }
}

```

**Comment by meeshoogendoorn** [comment]
The solution was to run the command `yarn add -D typescript@latest` now the error is gone but now i have overwritten the typescript that is user by your code.

he installed this version: `"typescript": "^4.3.2"`

**Comment by meeshoogendoorn** [comment]
With clean version of PWA i didn't had this problem. But i looked the whole code for possible recursive functions but found nothing.

**Comment by meeshoogendoorn** [comment]
@mkucmus The problem was in the SfTable component from storefront-ui.

```js
provide() {
    const table = {};
    Object.defineProperty(table, "updateColumnsCount", {
      value: this.updateColumnsCount,
    });
    return { table };
  },
```

This code above was returning in an exception `Object.defineProperty called on non-object` but in the typescript compiler it was not throwing this message. I will throw in issue in their repo.
