### ISSUE TITLE
[Bug] Not able to install the project. Missing "@shopware-pwa/default-theme"

### ISSUE THREAD

**Issue by jorenn92** [vuestorefront/shopware-pwa#1693]
### What happened?

When i try to install the application, the process throws an error right after generating the plugins files. 
I've tried with my own local shopware instance and the demo. Both result in the same error.

![image](https://user-images.githubusercontent.com/9069536/135313047-e703b6c9-25bf-4ba1-98f7-dc3dccf40efe.png)

### Steps To Reproduce

- Run  npx @shopware-pwa/cli init and follow the steps. 
- Wait for error

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Canary (generated by CLI)

### Which element is affected?

CLI

### Environment

```markdown
- OS: Ubuntu Linux amd64/x86
- Node: v15.14.0
- Shopware API: 6.4.4.1
- Shopware PWA version: Canary
```

### Relevant log output

```shell
Error: No theme found for "@shopware-pwa/default-theme". Please make sure that path is correct or theme is installed from NPM.
    at EmptyToolbox.toolbox.getThemePath (/root/.npm/_npx/dacb6bca730a8919/node_modules/@shopware-pwa/cli/build/extensions/shopware-pwa-extension.js:7687:11)
    at EmptyToolbox.toolbox.checkThemePath (/root/.npm/_npx/dacb6bca730a8919/node_modules/@shopware-pwa/cli/build/extensions/shopware-pwa-extension.js:7691:15)
    at Command.run (/root/.npm/_npx/dacb6bca730a8919/node_modules/@shopware-pwa/cli/build/commands/languages.js:8:13)
    at Runtime.<anonymous> (/root/.npm/_npx/dacb6bca730a8919/node_modules/gluegun/build/runtime/run.js:118:58)
    at step (/root/.npm/_npx/dacb6bca730a8919/node_modules/gluegun/build/runtime/run.js:44:23)
    at Object.next (/root/.npm/_npx/dacb6bca730a8919/node_modules/gluegun/build/runtime/run.js:25:53)
    at fulfilled (/root/.npm/_npx/dacb6bca730a8919/node_modules/gluegun/build/runtime/run.js:16:58)
```

**Comment by jorenn92** [comment]
It does work with version 14.15.3 on Windows 10. 
I never got it working on Linux. This specific error stopped occuring, but i got stuck on the node-sass error from #1311.
I gave up on Linux and finally got it to succesfully init on Windows.
