### ISSUE TITLE
[Bug] Replace refreshCart() in api-client.js

### ISSUE THREAD

**Issue by diogenesneves** [vuestorefront/shopware-pwa#1980]
### What happened?

I copied the api-client.js file from node_modules, hoping to be able to change the refreshCart function, but I am getting the following error.
ERROR  Could not compile template /home/app/pwa/.shopware-pwa/source/plugins/api-client.js: Cannot read property 'timeout' of undefined

### Steps To Reproduce

copy api-client.js to src/plugins

### Version

Previous versions (write which one)

### Which element is affected?

nuxt-module

### Environment

```markdown
- OS: ubuntu
- Node: 18.4.0
- Shopware API: 6.4.10
- Shopware PWA version: 1.4.0
```

### Relevant log output

```shell
ERROR  Could not compile template /home/app/pwa/.shopware-pwa/source/plugins/api-client.js: Cannot read property 'timeout' of undefined

  at node_modules/@nuxt/builder/dist/builder.js:723:17
  at async Promise.all (index 4)
  at async Builder.compileTemplates (node_modules/@nuxt/builder/dist/builder.js:701:5)
  at async Builder.generateRoutesAndFiles (node_modules/@nuxt/builder/dist/builder.js:388:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:319:5)
  at async Object._buildDev (node_modules/@nuxt/cli/dist/cli-dev.js:107:5)
  at async Object.startDev (node_modules/@nuxt/cli/dist/cli-dev.js:65:7)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
```

**Comment by diogenesneves** [comment]
Resolved
